environment: "development"
random_seed: 42
loader_workers: 4
max_files_cache: 1

preprocessing_config:
    print_class_imbalance: false
    preprocess: false
    split_ratio: 0.8

train_config:
    train: true
    resume_training: false
    resume_from: "trained_models/annealing.pth"
    batch_size: 8
    num_epochs: 100
    learning_rate: 0.0001
    eta_min_lr: 0.00001
    weighted_loss: true
    save_model: true
    model_name: "annealing.pth"
    loss_history_path: "models/loss_history/"

validation_config:
    model_path: "trained_models/new_model.pth"
    evaluate: false
    predict: false
    batch_size: 1

file_paths:
    raw_data: "data/raw/training/"
    preproc_data: "data/preproc/" # /train and /test
    model_save_path: "models/"
