environment: "development"
random_seed: 42
loader_workers: 2

preprocessing_config:
    print_class_imbalance: false
    preprocess: false
    split_ratio: 0.8

train_config:
    train: true
    resume_training: true
    resume_from: "trained_models/best_model_weighted.pth"
    batch_size: 8
    num_epochs: 200
    learning_rate: 0.00001
    weighted_loss: true
    save_model: true
    model_name: "new_model.pth"

validation_config:
    model_path: "trained_models/best_model_weighted.pth"
    evaluate: false
    predict: false
    batch_size: 1

file_paths:
    raw_data: "data/raw/training/"
    preproc_data: "data/preproc/" # /train and /test
    model_save_path: "models/"
