name: brats

channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults

dependencies:
  - python=3.10
  - pytorch=2.5.1
  - torchvision=0.20.1
  - pytorch-cuda=12.4
  - numpy
  - scipy
  - scikit-learn
  - matplotlib
  - pillow
  - pyyaml
  - requests
  - networkx
  - jinja2
  - jupyterlab
  - pip

  - pip:
      - monai==1.5.1
      - torchio==0.21.1
      - simpleitk==2.5.3
      - nibabel==5.3.3
      - seaborn==0.13.2
      - pandas==2.3.3
      - tqdm==4.67.1
      - split-folders
      - torchinfo
